### ISSUE TITLE
Не получается войти в базу MySql в Dbeaver и при прогоне автотестов

### ISSUE THREAD

**Issue by Smytstone** [Smytstone/Diploma#2]
# Описание
При попытке подключения к базе MySql - выдаёт ошибку Access denied for user 'app'@'172.18.0.1' (using password: YES)
При прогоне автотестов, автотесты где есть проверки данных в базе, выдаёт такую же ошибку Access denied for user 'app'@'172.18.0.1' (using password: YES).

# Шаги
1. В файле application properties ставим комментирование на строку с базой postgres и убираем с MySql 
2. Запускаем контейнер командой docker compose up 
3. В следующем окне командной строки переходим в папку artifacts командой cd artifacts 
4. Запускаем приложение командой java -jar ./aqa-shop.jar -Dspring.datasource.url=jdbc:mysql://localhost:3306/app
5. Выполняем тест shouldIgnorePaymentWithDeclinedCreditCard()

# Ожидаемый результат 
В базу данных можно зайти и проверить информацию

# Фактический результат 
В базу нельзя зайти по причине отказа в доступе

![MySql ошибка](https://github.com/user-attachments/assets/1b8376b1-4db6-471e-820a-6f54a9d489a4)
![MySql ошибка2](https://github.com/user-attachments/assets/dd4bbf34-7f38-4571-8b32-11d00de29be1)

# Окружение
* **Операционная система:** Windows 10
* **Браузер:** Версия 126.0.6478.127 (Официальная сборка), (64 бит)

* **IDE:** IntelliJ IDEA Community Edition 2023.3.4
* **Java:** OpenJDK 11

**Comment by ArRomanov** [comment]
1. Причиной того, что приложение и dbeaver не подключается к БД может быть установленный mysql на вашем ПК. Подскажите, устанавливали ли вы mysql локально на ПК? Если да, то значит он конфликтует с запущенными контейнерами. Необходимо с ПК удалить и использовать БД только в контейнере 
2. Кроме этого у вас в этом [файле](https://github.com/Smytstone/Diploma/blob/6c0fc95a1a787ad92324299a767756872f5cab2d/src/test/java/ru/netology/data/DataBase.java#L16) некорректно заданы параметры для подключения к БД. Вы прописали названия параметров из файла application.properties и взяли их в кавычки. Код интерпретирует эти данные как адрес БД, логин и пароль и, соответственно, не сможет подключиться к БД. Как работать с этими параметрами опишу ниже.

Приложение. У вас в application.properties заданы параметры для подключения к БД. Также, эти параметры можно задать другим способом - в командной строке. Чтобы не изменять код, но поменять параметры подключения мы просто запускаем приложение с использованием обновленных параметров (точно с такими же именами как в файле) - java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/kuularbase -Dspring.datasource.username=kuular -Dspring.datasource.password=12345v -jar aqa-shop.jar. Иногда в windows нужно добавить кавычки - java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/kuularbase" "-Dspring.datasource.username=kuular" "-Dspring.datasource.password=12345v" -jar aqa-shop.jar

С тестами чуть больше действий. а) определить переменные окружения в build.gradle аналогично тому, как у вас определена selenide.headless. Именовать новые параметры можете как угодно б) В коде, чтобы получить значения этих переменных, мы делаем так - var value = System.getProperty("your.parameter"); в) а передаем значения этих переменных так же в командной строке - ./gradlew test -Dyour.parameter=your_value. Новые переменные можете именовать как угодно, важно, чтобы имена в командной строке, в файле build.gradle и в коде совпадали. И последнее: для этих переменных можно задать в build.gradle значения по умолчанию, они будут применяться, если в командной строке параметры не переданы или если вы запускаете тесты не из терминала, а кнопкой в ide. Выглядит в build.gradle это так - systemProperty 'your.parameter', System.getProperty('your.parameter', "default_value")
